import asyncio
from fastapi import APIRouter
from datetime import datetime, timedelta, timezone
import json
import os
from db.supabase import supabase
from langchain_mistralai import ChatMistralAI
from langchain_core.messages import HumanMessage, SystemMessage

router = APIRouter()

@router.get("/health-data/{user_id}")
async def get_health_data(user_id: str):
    try:
        def _fetch():
            latest = supabase.table("ring_data")\
                .select("*")\
                .eq("user_id", user_id)\
                .order("recorded_at", desc=True)\
                .limit(1)\
                .execute()

            weekly = supabase.table("ring_data")\
                .select("*")\
                .eq("user_id", user_id)\
                .order("recorded_at", desc=True)\
                .limit(7)\
                .execute()
            return latest, weekly

        # Both blocking Supabase calls run off the event loop together — a
        # blocking call here previously froze the whole server for every
        # other concurrent request (insights, chat, history), not just this one.
        latest, weekly = await asyncio.to_thread(_fetch)

        weekly_avg = None
        if weekly.data:
            days = weekly.data
            weekly_avg = {
                "avg_sleep": sum(d.get("sleep_duration_minutes", 0) for d in days) / len(days),
                "avg_hr": sum(d.get("heart_rate_avg", 0) for d in days) / len(days),
                "avg_steps": sum(d.get("steps", 0) for d in days) / len(days),
                "avg_spo2": sum(d.get("spo2_avg", 0) for d in days) / len(days),
                "avg_sleep_score": sum(d.get("sleep_score", 0) for d in days) / len(days),
            }

        return {
            "latest": latest.data[0] if latest.data else None,
            "weekly_avg": weekly_avg,
        }
    except Exception as e:
        return {"error": str(e)}


# ── Dynamic insights (headline + key-change cards) ─────────────────────────
#
# Everything below is computed from real rows in the DB for the requested
# range, split into an "earlier half" and a "later half" so we can measure a
# genuine trend rather than a single snapshot. The headline/subtext copy is
# then generated by an LLM grounded strictly in that computed `changes` data
# (never given raw DB access, never allowed to invent a number) — with a
# deterministic template fallback if the LLM call fails or returns something
# unparseable, so this endpoint is never blank or broken.
#
# IMPORTANT: every supabase.table(...).execute() call and every LLM .invoke()
# call is synchronous/blocking. Run directly inside this async route, any one
# of them freezes FastAPI's entire single-threaded event loop — meaning every
# OTHER concurrent request (other users' /insights, /chat, /history calls)
# queues up and stalls until this one finishes, even though they have nothing
# to do with each other. That was the actual cause of the multi-minute
# request pileups seen in Railway's logs. Wrapping each blocking call in
# asyncio.to_thread() runs it on a background thread instead, freeing the
# event loop to keep serving other requests while this one waits on I/O.

RANGE_DAYS = {"7D": 7, "30D": 30, "90D": 90}


def _format_hm(total_minutes: int) -> str:
    """Format a minute count as a compact days/hours/minutes string, e.g. 150 -> '2h 30m',
    60 -> '1h', 45 -> '45m', 1500 -> '1d 1h'. Used so sleep deltas read in
    human units instead of raw minutes or overflowing hour counts."""
    total_minutes = abs(total_minutes)
    d = total_minutes // 1440
    h = (total_minutes % 1440) // 60
    m = total_minutes % 60
    if d > 0 and h > 0:
        return f"{d}d {h}h"
    if d > 0:
        return f"{d}d"
    if h > 0 and m > 0:
        return f"{h}h {m}m"
    if h > 0:
        return f"{h}h"
    return f"{m}m"


async def _rows_in_range(table: str, user_id: str, days: int, date_col: str):
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).date().isoformat()

    def _query():
        return supabase.table(table)\
            .select("*")\
            .eq("user_id", user_id)\
            .gte(date_col, cutoff)\
            .order(date_col, desc=False)\
            .execute()

    r = await asyncio.to_thread(_query)
    return r.data or []

def _split_avg(rows, field):
    """Average `field` over the first half vs second half of `rows` (chronological)."""
    vals = [r.get(field) for r in rows if r.get(field) is not None]
    if len(vals) < 2:
        return None, None
    mid = len(vals) // 2
    first_half = vals[:mid] if mid > 0 else vals[:1]
    second_half = vals[mid:]
    if not first_half or not second_half:
        return None, None
    return sum(first_half) / len(first_half), sum(second_half) / len(second_half)

async def _bp_rows_in_range(user_id: str, days: int):
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()

    def _query():
        return supabase.table("user_bp")\
            .select("*")\
            .eq("user_id", user_id)\
            .gte("measured_at", cutoff)\
            .order("measured_at", desc=False)\
            .execute()

    r = await asyncio.to_thread(_query)
    return r.data or []


async def _measured_at_rows_in_range(table: str, user_id: str, days: int):
    """Like _rows_in_range but for tables keyed on measured_at instead of date
    (user_stress, user_temp) — mirrors _bp_rows_in_range's pattern."""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()

    def _query():
        return supabase.table(table)\
            .select("*")\
            .eq("user_id", user_id)\
            .gte("measured_at", cutoff)\
            .order("measured_at", desc=False)\
            .execute()

    r = await asyncio.to_thread(_query)
    return r.data or []


# ── LLM headline/subtext generation ─────────────────────────────────────────

INSIGHTS_SYSTEM_PROMPT = """You are writing a short, precise health insight headline and subtext for a smart ring app's home screen.

You will be given a JSON list of pre-computed, real metric changes for the user over a period — each with a title, a delta label, a subtitle describing what changed, and whether it's alarming. You must NOT invent, estimate, or add any number, metric, or claim that isn't in the given list. If the list is empty, say there isn't enough data yet.

Respond with STRICT JSON only — no markdown, no code fences, no commentary before or after. Match this exact shape:

{
  "headline_parts": [
    {"text": "Your sleep is steadier, but blood pressure is ", "highlight": false},
    {"text": "high", "highlight": true}
  ],
  "subtext": "One or two plain-language sentences elaborating, grounded only in the given changes."
}

Rules:
- The headline should read like a short, human sentence (max ~15 words), split into headline_parts so exactly one clause can be highlighted — set highlight: true only on the most notable or concerning clause, based on which items in the list are marked alarming.
- If any item is alarming, the headline and subtext should center on that item specifically, by its exact title and subtitle wording given.
- If nothing is alarming, write an encouraging but honest headline reflecting the real changes given (e.g. improving trends).
- If the list is empty, headline_parts should read "Not enough data yet to show trends" (highlight: false), and subtext should briefly explain to keep wearing the ring.
- Never mention a metric, number, or claim that is not present in the given list."""


def _template_headline(changes: list, alarming_changes: list) -> dict:
    """Deterministic fallback if the LLM call fails or returns unparseable
    output — same logic this endpoint used before, built only from real
    computed changes, never invented."""
    if not changes:
        return {
            "headline_parts": [{"text": "Not enough data yet to summarize your trends.", "highlight": False}],
            "subtext": "Keep wearing your ring and check back after a few more days of readings.",
        }
    if alarming_changes:
        worst = alarming_changes[0]
        headline_parts = [
            {"text": f"Your {worst['title'].lower()} needs attention", "highlight": False},
        ]
        other_improving = [c["title"] for c in changes if c.get("improving") and not c["alarming"]]
        if other_improving:
            subtext = f"{', '.join(other_improving)} improved this period, but {worst['title'].lower()} needs closer attention. See the details below."
        else:
            subtext = f"{worst['title']} needs closer attention this period. See the details below."
        return {"headline_parts": headline_parts, "subtext": subtext}

    improving = [c["title"] for c in changes if c.get("improving")]
    declining = [c["title"] for c in changes if not c.get("improving")]
    if improving and not declining:
        headline_parts = [{"text": "Your recovery is trending in the right direction", "highlight": False}]
    elif improving and declining:
        headline_parts = [
            {"text": f"{', '.join(improving)} improved, but ", "highlight": False},
            {"text": declining[0].lower(), "highlight": True},
            {"text": " needs a closer look", "highlight": False},
        ]
    else:
        headline_parts = [{"text": "A few metrics need a closer look", "highlight": False}]
    subtext = "Select any change below for more detail."
    return {"headline_parts": headline_parts, "subtext": subtext}


async def _call_llm_for_headline(changes: list, alarming_changes: list) -> dict:
    payload = json.dumps({
        "changes": [
            {
                "title": c["title"],
                "delta_label": c["delta_label"],
                "subtitle": c["subtitle"],
                "alarming": c["alarming"],
            }
            for c in changes
        ]
    }, indent=2)

    llm = ChatMistralAI(
        api_key=os.getenv("MISTRAL_API_KEY"),
        model="mistral-large-latest",
        temperature=0.2,
    )
    # await .ainvoke(), not the blocking .invoke() — this single call was the
    # single biggest contributor to the multi-minute request pileups: while
    # waiting on Mistral's response, .invoke() froze the entire event loop,
    # blocking every other concurrent user's request regardless of endpoint.
    result = await llm.ainvoke([
        SystemMessage(content=INSIGHTS_SYSTEM_PROMPT),
        HumanMessage(content=payload),
    ])
    raw = result.content.strip()
    start = raw.find("{")
    end = raw.rfind("}")
    if start == -1 or end == -1:
        raise ValueError("No JSON object found in LLM response")
    parsed = json.loads(raw[start:end + 1])
    if "headline_parts" not in parsed or "subtext" not in parsed:
        raise ValueError("Malformed insights JSON from LLM")
    return parsed


STEADY_STATUS_SYSTEM_PROMPT = """You are writing a short, warm health status headline and subtext for a smart ring app.

Nothing in the user's data changed significantly this period — all their vitals are steady. You will be given a JSON list of their current readings (metric name and value, in plain text). Write an encouraging, natural-sounding headline and subtext that reflects these readings.

Respond with STRICT JSON only — no markdown, no code fences, no commentary. Match this exact shape:

{
  "headline_parts": [
    {"text": "Your vitals look ", "highlight": false},
    {"text": "steady", "highlight": true}
  ],
  "subtext": "One short, natural sentence mentioning the readings given."
}

Rules:
- Never invent, estimate, or add any number or metric not present in the given list.
- Keep the headline under ~10 words, with exactly one highlighted clause (usually the encouraging word itself, e.g. "steady", "on track", "in good shape").
- The subtext should read like a natural sentence weaving in the given readings, not a bare comma-separated list.
- Tone: warm, brief, reassuring — not clinical."""


async def _call_llm_for_steady_status(current_status_parts: list) -> dict:
    payload = json.dumps({"current_readings": current_status_parts}, indent=2)

    llm = ChatMistralAI(
        api_key=os.getenv("MISTRAL_API_KEY"),
        model="mistral-large-latest",
        temperature=0.2,
    )
    result = await llm.ainvoke([
        SystemMessage(content=STEADY_STATUS_SYSTEM_PROMPT),
        HumanMessage(content=payload),
    ])
    raw = result.content.strip()
    start = raw.find("{")
    end = raw.rfind("}")
    if start == -1 or end == -1:
        raise ValueError("No JSON object found in LLM response")
    parsed = json.loads(raw[start:end + 1])
    if "headline_parts" not in parsed or "subtext" not in parsed:
        raise ValueError("Malformed steady-status JSON from LLM")
    return parsed


@router.get("/insights/{user_id}")
async def get_insights(user_id: str, range: str = "30D"):
    days = RANGE_DAYS.get(range, 30)
    try:
        changes = []  # each: dict(key,title,delta_label,subtitle,alarming,improving)
        # Collected regardless of whether a metric "changed" — used for the
        # Tier 2 steady-vitals summary when nothing trended significantly.
        current_status_parts = []

        # --- Sleep (user_sleep: date, total_duration [minutes], sleep_score) ---
        sleep_rows = await _rows_in_range("user_sleep", user_id, days, "date")
        valid_sleep_rows = [r for r in sleep_rows if (r.get("total_duration") or 0) > 0]
        first, second = _split_avg(valid_sleep_rows, "total_duration")
        latest_sleep = valid_sleep_rows[-1].get("total_duration") if valid_sleep_rows else None
        if latest_sleep:
            current_status_parts.append(f"sleep {_format_hm(latest_sleep)}")
        if first is not None:
            delta_min = round(second - first)
            if abs(delta_min) >= 15:
                improving = delta_min > 0
                changes.append({
                    "key": "sleep",
                    "title": "Sleep",
                    "delta_label": f"{'+' if delta_min >= 0 else '-'}{_format_hm(delta_min)}",
                    "subtitle": f"{_format_hm(delta_min)} {'more' if improving else 'less'} sleep on average",
                    "alarming": (not improving) and abs(delta_min) >= 30,
                    "improving": improving,
                })

        # --- HRV (user_hrv: date, avg_hrv ms) — lower HRV trend is the concern ---
        hrv_rows = await _rows_in_range("user_hrv", user_id, days, "date")
        valid_hrv_rows = [r for r in hrv_rows if (r.get("avg_hrv") or 0) > 0]
        first, second = _split_avg(valid_hrv_rows, "avg_hrv")
        latest_hrv = valid_hrv_rows[-1].get("avg_hrv") if valid_hrv_rows else None
        if latest_hrv:
            current_status_parts.append(f"HRV {round(latest_hrv)} ms")
        if first is not None:
            delta_hrv = round(second - first)
            if abs(delta_hrv) >= 4:
                improving = delta_hrv > 0
                changes.append({
                    "key": "hrv",
                    "title": "HRV",
                    "delta_label": f"{'+' if delta_hrv >= 0 else ''}{delta_hrv} ms",
                    "subtitle": f"Heart rate variability {'improved' if improving else 'dropped'} across the period",
                    "alarming": (not improving) and abs(delta_hrv) >= 10,
                    "improving": improving,
                })

        # --- Resting heart rate (user_hr: date, avg_hr) ---
        hr_rows = await _rows_in_range("user_hr", user_id, days, "date")
        valid_hr_rows = [r for r in hr_rows if (r.get("avg_hr") or 0) > 0]
        first, second = _split_avg(valid_hr_rows, "avg_hr")
        latest_avg_hr = valid_hr_rows[-1].get("avg_hr") if valid_hr_rows else None
        if latest_avg_hr:
            current_status_parts.append(f"heart rate {round(latest_avg_hr)} bpm")
        if first is not None:
            delta_hr = round(second - first)
            alarming = latest_avg_hr is not None and latest_avg_hr >= 100
            if abs(delta_hr) >= 5 or alarming:
                improving = delta_hr <= 0
                changes.append({
                    "key": "heart_rate",
                    "title": "Heart rate",
                    "delta_label": f"{'+' if delta_hr >= 0 else ''}{delta_hr} bpm",
                    "subtitle": (
                        f"Resting heart rate elevated, averaging {round(latest_avg_hr)} bpm recently"
                        if alarming else
                        f"Resting heart rate trending {'up' if delta_hr > 0 else 'down'} across the period"
                    ),
                    "alarming": alarming,
                    "improving": improving,
                })

        # --- Blood pressure (user_bp: measured_at, systolic, diastolic) ---
        bp_rows = await _bp_rows_in_range(user_id, days)
        first_s, second_s = _split_avg(bp_rows, "systolic")
        latest_systolic = bp_rows[-1].get("systolic") if bp_rows else None
        latest_diastolic = bp_rows[-1].get("diastolic") if bp_rows else None
        if latest_systolic and latest_diastolic:
            current_status_parts.append(f"blood pressure {latest_systolic}/{latest_diastolic}")
        if first_s is not None:
            delta_s = round(second_s - first_s)
            hypertensive = (latest_systolic and latest_systolic >= 130) or (latest_diastolic and latest_diastolic >= 80)
            if abs(delta_s) >= 5 or hypertensive:
                improving = delta_s <= 0
                alarming = hypertensive
                changes.append({
                    "key": "blood_pressure",
                    "title": "Blood pressure",
                    "delta_label": f"{'+' if delta_s >= 0 else ''}{delta_s}",
                    "subtitle": (
                        f"Systolic trending up across the period, latest {latest_systolic}/{latest_diastolic}"
                        if alarming else
                        "Systolic trending down across the period"
                    ),
                    "alarming": alarming,
                    "improving": improving,
                })

        # --- SpO2 (user_spo2: date, avg_spo2) — alarming if genuinely low ---
        spo2_rows = await _rows_in_range("user_spo2", user_id, days, "date")
        latest_spo2 = spo2_rows[-1].get("avg_spo2") if spo2_rows else None
        if latest_spo2:
            current_status_parts.append(f"SpO2 {round(latest_spo2)}%")
        if latest_spo2 is not None and latest_spo2 < 94:
            changes.append({
                "key": "spo2",
                "title": "Blood oxygen",
                "delta_label": f"{round(latest_spo2)}%",
                "subtitle": f"Recent SpO2 reading of {round(latest_spo2)}% is below the normal range",
                "alarming": True,
                "improving": False,
            })

        # --- Steps (user_steps: date, steps) ---
        steps_rows = await _rows_in_range("user_steps", user_id, days, "date")
        valid_steps_rows = [r for r in steps_rows if (r.get("steps") or 0) > 0]
        first, second = _split_avg(valid_steps_rows, "steps")
        latest_steps = valid_steps_rows[-1].get("steps") if valid_steps_rows else None
        if latest_steps:
            current_status_parts.append(f"{latest_steps:,} steps")
        if first and first > 0:
            pct = round(((second - first) / first) * 100)
            if abs(pct) >= 20:
                improving = pct > 0
                changes.append({
                    "key": "steps",
                    "title": "Activity",
                    "delta_label": f"{'+' if pct >= 0 else ''}{pct}%",
                    "subtitle": f"Daily steps {'up' if improving else 'down'} {abs(pct)}% across the period",
                    "alarming": False,
                    "improving": improving,
                })

        # --- Stress (user_stress: measured_at, stress_value, label) ---
        # Lower stress trend = improving, mirrors the HRV pattern.
        stress_rows = await _measured_at_rows_in_range("user_stress", user_id, days)
        first, second = _split_avg(stress_rows, "stress_value")
        latest_stress_row = stress_rows[-1] if stress_rows else None
        latest_stress_val = latest_stress_row.get("stress_value") if latest_stress_row else None
        latest_stress_label = latest_stress_row.get("label") if latest_stress_row else None
        if latest_stress_val is not None:
            label_suffix = f" ({latest_stress_label.lower()})" if latest_stress_label else ""
            current_status_parts.append(f"stress {latest_stress_val}{label_suffix}")
        if first is not None:
            delta_stress = round(second - first)
            if abs(delta_stress) >= 8:
                improving = delta_stress < 0
                changes.append({
                    "key": "stress",
                    "title": "Stress",
                    "delta_label": f"{'+' if delta_stress >= 0 else ''}{delta_stress}",
                    "subtitle": (
                        f"Stress trending {'up' if delta_stress > 0 else 'down'} across the period"
                        if not (latest_stress_val is not None and latest_stress_val >= 80) else
                        f"Recent stress reading of {latest_stress_val} is elevated"
                    ),
                    "alarming": latest_stress_val is not None and latest_stress_val >= 80,
                    "improving": improving,
                })

        # --- Temperature (user_temp: measured_at, value_c) ---
        # Alarming if the latest reading is outside a normal range, mirroring
        # the SpO2 "latest value" style check rather than a trend delta.
        temp_rows = await _measured_at_rows_in_range("user_temp", user_id, days)
        latest_temp = temp_rows[-1].get("value_c") if temp_rows else None
        if latest_temp:
            current_status_parts.append(f"temperature {latest_temp:.1f}°C")
        if latest_temp is not None and (latest_temp < 36.1 or latest_temp > 37.5):
            changes.append({
                "key": "temperature",
                "title": "Temperature",
                "delta_label": f"{latest_temp:.1f}°C",
                "subtitle": (
                    f"Recent temperature reading of {latest_temp:.1f}°C is elevated"
                    if latest_temp > 37.5 else
                    f"Recent temperature reading of {latest_temp:.1f}°C is below normal"
                ),
                "alarming": True,
                "improving": False,
            })

        # If anything is alarming, only alarming card(s) are surfaced.
        alarming_changes = [c for c in changes if c["alarming"]]
        if alarming_changes:
            updates = alarming_changes
        else:
            updates = changes[:2]

        # --- Headline + subtext ---
        if changes:
            try:
                headline_data = await _call_llm_for_headline(changes, alarming_changes)
            except Exception as e:
                print(f"[get_insights] LLM headline generation failed, using template fallback: {e}")
                headline_data = _template_headline(changes, alarming_changes)
        elif current_status_parts:
            # Tier 2: nothing changed significantly, but real current readings
            # exist — show an LLM-phrased steady-vitals status summary instead
            # of a bare "not enough data" message, with a deterministic
            # template fallback if the LLM call fails.
            try:
                headline_data = await _call_llm_for_steady_status(current_status_parts)
            except Exception as e:
                print(f"[get_insights] LLM steady-status generation failed, using template fallback: {e}")
                headline_data = {
                    "headline_parts": [
                        {"text": "Your vitals look ", "highlight": False},
                        {"text": "steady", "highlight": True},
                    ],
                    "subtext": f"Latest readings: {', '.join(current_status_parts)}.",
                }
        else:
            headline_data = _template_headline(changes, alarming_changes)

        return {
            "range": range,
            "headline_parts": headline_data["headline_parts"],
            "subtext": headline_data["subtext"],
            "updates": [
                {
                    "key": c["key"],
                    "title": c["title"],
                    "delta_label": c["delta_label"],
                    "subtitle": c["subtitle"],
                    "alarming": c["alarming"],
                }
                for c in updates
            ],
        }
    except Exception as e:
        return {"error": str(e)}